version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AbstractBusines
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/AbstractBusines

volumes:
  postgres-data: